#!/usr/bin/python
from optparse import OptionParser, make_option
import sys
import dbus

bus = dbus.SystemBus()

option_list = [ make_option("-p", "--path", action="store", type="string", dest="path"), ]
parser = OptionParser(option_list=option_list)

(options, args) = parser.parse_args()

if (len(args) < 1):
        print("Usage: %s <command>" % (sys.argv[0]))
        print("")
        print("  info")
        print("  powered [on/off]")
        sys.exit(1)

cmd = args[0]
if (options.path):
	path = options.path
else:
	path = "/wpan0"

props = dbus.Interface(bus.get_object("net.connman.iwpand", path), "org.freedesktop.DBus.Properties")

if (cmd == "info"):
	print (props.GetAll("net.connman.iwpand.Adapter"))
	sys.exit(0)

if (cmd == "panid"):
	panid = props.Get("net.connman.iwpand.Adapter", "PanId")
	if (len(args) < 2):
		print("  PanId: %d" % panid)
	else:
		new_panid = dbus.UInt16(int(args[1]))
		props.Set("net.connman.iwpand.Adapter", "PanId", new_panid)
		new_panid = props.Get("net.connman.iwpand.Adapter", "PanId")
		print ("  Channel: %d > %d" % (panid, new_panid))

	sys.exit(0)

if (cmd == "powered"):
	print ("powered ...")
	powered1 = props.Get("net.connman.iwpand.Adapter", "Powered")
	if (len(args) < 2):
		print("  Powered: %d" % powered1)
	else:
		if (args[1] == "on"):
			value = dbus.Boolean(1)
		else:
			value = dbus.Boolean(0)

		props.Set("net.connman.iwpand.Adapter", "Powered", value)
		powered2 = props.Get("net.connman.iwpand.Adapter", "Powered")
		print ("  Powered: %d > %d" % (powered1, powered2))

	sys.exit(0)
